### ISSUE TITLE
Feature Request: Support new authorization on the newest firmwares

### ISSUE THREAD

**Issue by mafr95** [JurajNyiri/HomeAssistant-Tapo-Control#436]
### Description

Yesterday I updated my Tapo C210 camera to version 1.3.9. After that, the integration could no longer connect to the camera. I decided to delete the camera from the integration and add it again. But every time I enter my cloud password, the error message "Invalid cloud password" appears.  I have now checked the password 10 times. It is definitely correct.  I suspect it has something to do with the camera update. Previously it worked without any problems. 

I have two other cameras. (C200 and C220) I was able to add them with the same cloud password without any problems.

In the meantime, I removed the camera from the Tapo app, reset it and added it again. But without success.

### Reproduction Steps

1. Update C210 to version 1.3.9 Build 231019 Rel. 13805n(4555)
2. Add camera in tapo integration
3. Enter correct ip adress
4. Enter correct username and passwort for camera account (created via tapo app)
5. Enter cloud password ==> failed 

### Expected behavior

Add camera to integration

### Device Firmware

1.3.9 Build 231019 Rel. 13805n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

RPI 4

### Search for similar issues

Yes

**Comment by umaito** [comment]
I have the same issue with thé cloud password. And I updated my tapo C210 too

**Comment by ramonrodriguezdiez** [comment]
I have the same issue, C210 and updated to 1.3.9

**Comment by kwermeister** [comment]
I have the same issue, C210 and updated to 1.3.9. 
2x C210 with 1.3.7. works fine.

**Comment by imperadeiro** [comment]
Same problem

**Comment by JurajNyiri** [comment]
Looks like they changed how the authorization work. Someone will need to inspect the communication and find a new proper username and password for videos playback / control on some cameras, then we can update the integration.

**Comment by JurajNyiri** [comment]
Try running this script:

```
from pytapo import Tapo

user = ""  # 3rd party account name
password = ""  # 3rd party account password
password_cloud = ""  # cloud password
host = ""  # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, "admin", password_cloud)

request = tapo.getBasicInfo()
print(request)

tapo = Tapo(host, user, password)

request = tapo.getBasicInfo()
print(request)
```

Expected response would be the same output twice containing information about camera. Make sure to fill in the 4 variables.

**Comment by mafr95** [comment]
I get this output:

`Traceback (most recent call last):
  File "/home/pi/testtapo.py", line 7, in <module>
    tapo = Tapo(host, "admin", password_cloud)
  File "/home/pi/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 53, in __init__
    self.basicInfo = self.getBasicInfo()
  File "/home/pi/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 554, in getBasicInfo
    return self.executeFunction(
  File "/home/pi/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 142, in executeFunction
    data = self.performRequest(
  File "/home/pi/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 171, in performRequest
    self.ensureAuthenticated()
  File "/home/pi/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 73, in ensureAuthenticated
    return self.refreshStok()
  File "/home/pi/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 121, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
`

**Comment by JurajNyiri** [comment]
Please post the full output, not just the error.

**Comment by JurajNyiri** [comment]
Could you try this:

```
from pytapo import Tapo

user = ""  # 3rd party account name
password = ""  # 3rd party account password
password_cloud = ""  # cloud password
host = ""  # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

request = tapo.getBasicInfo()
print(request)

tapo = Tapo(host, "admin", password_cloud)

request = tapo.getBasicInfo()
print(request)
```

**Comment by JurajNyiri** [comment]
If you get access working via the 3rd party account, can you try if control works? Try setting for example privacy mode https://github.com/JurajNyiri/pytapo/blob/main/pytapo/__init__.py#L567 .

**Comment by fetsreg** [comment]
Hi, I have the same issue with my C210 running on 1.3.9, even the authentication with the local camera account is failing:
`PS C:\Users\local\Repos\Tapo> python .\tapo.py   
Traceback (most recent call last):
  File "C:\Users\local\Repos\Tapo\tapo.py", line 8, in <module>
    tapo = Tapo(host, user, password)
  File "C:\Users\local\Repos\Tapo\.venv\lib\site-packages\pytapo\__init__.py", line 53, in __init__
    self.basicInfo = self.getBasicInfo()
  File "C:\Users\local\Repos\Tapo\.venv\lib\site-packages\pytapo\__init__.py", line 554, in getBasicInfo
    return self.executeFunction(
  File "C:\Users\local\Repos\Tapo\.venv\lib\site-packages\pytapo\__init__.py", line 142, in executeFunction
    data = self.performRequest(
  File "C:\Users\local\Repos\Tapo\.venv\lib\site-packages\pytapo\__init__.py", line 171, in performRequest
    self.ensureAuthenticated()
  File "C:\Users\local\Repos\Tapo\.venv\lib\site-packages\pytapo\__init__.py", line 73, in ensureAuthenticated
    return self.refreshStok()
  File "C:\Users\local\Repos\Tapo\.venv\lib\site-packages\pytapo\__init__.py", line 121, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data`

**Comment by JurajNyiri** [comment]
Make sure to always restart the camera before executing and not use it anywhere else (including the official app) as there is limited number of control slots available.

**Comment by fetsreg** [comment]
It is the same behavior with local authentication not working, even after a fresh reboot

**Comment by JurajNyiri** [comment]
That is different to what was reported in OP. Let's wait for more users to try this eliminate user error or camera weirdness.

In any case, we will need someone to sniff the traffic going from phone to camera on firmware 1.3.9 and see what is done differently, only then I can start working on the fix.

Guide: https://httptoolkit.com/docs/guides/android/ including the part "Intercepting traffic from 3rd party Android apps with certificate pinning"

**Comment by viprapp** [comment]
I'm here to report the same behavior with my Tapo C210 after updating to 1.3.9. Along with others, I've encountered the 'Invalid cloud password' error through the Home Assistant integration and an 'Exception: Invalid authentication data' error when using the suggested Python login script. Notably, my Synology DiskStation (Surveillance Station) still manages to connect using third-party login credentials. From memory, the update notes mentioned enhanced security measures in the authentication process. This could mean that what we're seeing might be the start of broader issues as similar authentication updates roll out to other Tapo cameras.

**Comment by cnecrea** [comment]
> ### Description
> Yesterday I updated my Tapo C210 camera to version 1.3.9. After that, the integration could no longer connect to the camera. I decided to delete the camera from the integration and add it again. But every time I enter my cloud password, the error message "Invalid cloud password" appears. I have now checked the password 10 times. It is definitely correct. I suspect it has something to do with the camera update. Previously it worked without any problems.
> 
> I have two other cameras. (C200 and C220) I was able to add them with the same cloud password without any problems.
> 
> In the meantime, I removed the camera from the Tapo app, reset it and added it again. But without success.
> 
> ### Reproduction Steps
> 1. Update C210 to version 1.3.9 Build 231019 Rel. 13805n(4555)
> 2. Add camera in tapo integration
> 3. Enter correct ip adress
> 4. Enter correct username and passwort for camera account (created via tapo app)
> 5. Enter cloud password ==> failed
> 
> ### Expected behavior
> Add camera to integration
> 
> ### If applicable, add error logs.
> _No response_
> 
> ### Device Firmware
> 1.3.9 Build 231019 Rel. 13805n(4555)
> 
> ### Using stream component
> Yes
> 
> ### Does camera work via official integrations?
> Yes
> 
> ### Camera has all attributes filled out in developer tools
> Yes
> 
> ### HASS Environment
> RPI 4
> 
> ### Search for similar issues
> Yes
> 
> ### Additional information
> _No response_

Same thing happens after firmware upgrade.

**Comment by JurajNyiri** [comment]
I have pushed a new code: https://github.com/JurajNyiri/pytapo/tree/debug_new_firmware

Download it manually, and next to README.md create file test.py with content:
```
from pytapo import Tapo

# Camera
user = ""  # 3rd party account name
password = ""  # 3rd party account password
password_cloud = ""  # cloud password
host = ""  # ip of the camera, example: 192.168.1.52

try:
    tapo = Tapo(host, "admin", password_cloud)
    request = tapo.getBasicInfo()
    print(request)
except Exception:
    pass

try:
    tapo = Tapo(host, user, password)

    request = tapo.getBasicInfo()
    print(request)
except Exception:
    pass
```

Post the whole output of the script.

**Comment by viprapp** [comment]
pyTapo - Version for debugging new firmware
True
admin
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
200
{"error_code": -40413, "result" : { "data": {"code": -40401, "encrypt_type": ["3"], "key": "REDACTED", "nonce": "REDACTED", "device_confirm": "REDACTED"}}}
pyTapo - Version for debugging new firmware
True
[USERNAME REDACTED]
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
200
{"error_code": -40401, "result" : { "data": {"code": -40411, "encrypt_type": ["1", "2"], "key": "REDACTED", "nonce": "REDACTED"}}}

**Comment by GSzabados** [comment]
@JurajNyiri, that is INVALID_NONCE(-40413).

**Comment by JurajNyiri** [comment]
@viprapp what is inside device_confirm? That field is new.

**Comment by viprapp** [comment]
Each time the script is executed, the 'device_confirm' field generates an 80-character, uppercase hexadecimal string, while the first 'nonce' (associated with 'admin') is 16 characters in uppercase hexadecimal format. The second 'nonce' (related to 'username') produces an 8-character alphanumeric string. 'device_confirm' and both 'nonces' change with every run of the script.

Also, inputting an incorrect cloud password doesn't alter the script's output, with the exception of the 'nonces' and 'device_confirm' fields, which are regenerated.

**Comment by viprapp** [comment]
Looks like some progress

```
pyTapo - Version for debugging new firmware 2
True
admin
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
200
{"error_code": 0, "result" : { "stok": "REDACTED", "user_group": "root", "start_seq": 0}}
pyTapo - Version for debugging new firmware 2
True
[USERNAME REDACTED]
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
200
{"error_code": -40401, "result" : { "data": {"code": -40411, "encrypt_type": ["1", "2"], "key": "REDACTED", "nonce": "REDACTED"}}}
```

**Comment by JurajNyiri** [comment]
Woah! That was unexpected.

Try now again, pushed more debug changes, new script (below variables):

```
tapo = Tapo(host, "admin", password_cloud)
request = tapo.getBasicInfo()
print(request)
```

**Comment by GSzabados** [comment]
@viprapp, could you also make sure that you have set up the non-admin local account in the Tapo app and you are using the right password for that?

**Comment by JurajNyiri** [comment]
@GSzabados I think this is the case of a camera refusing control without admin acc, there are cameras like that out, for example C200v3 C310 and probably C210 as well. That is why we default to control via admin acc in the integration.

**Comment by GSzabados** [comment]
Are those the Homekit compatible cameras?

**Comment by viprapp** [comment]
> @viprapp, could you also make sure that you have set up the non-admin local account in the Tapo app and you are using the right password for that?


Yes, I've consistently used the same local non-admin username and password for all tests, which were set up in the Tapo app. This is further corroborated by the fact that my Synology Surveillance Station can still connect to the C210 camera using these third-party credentials without any issues. This seems to align with JurajNyiri's hypothesis regarding the admin account behavior post-update.

**Comment by JurajNyiri** [comment]
@viprapp please take a look at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/436#issuecomment-1792572589 when you have the time.

**Comment by viprapp** [comment]
```
pyTapo - Version for debugging new firmware 3
getBasicInfo
executeFunction
True
admin
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'REDACTED', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
{"error_code": 0, "result": {"stok": "REDACTED", "user_group": "root", "start_seq": 0}}
200
{"error_code": 0, "result": {"stok": "REDACTED", "user_group": "root", "start_seq": 0}}
{"error_code":0,"seq":0,"result":{"response":"REDACTED"}}
Traceback (most recent call last):
  File "../pytapo_debug/test.py", line 8, in <module>
    tapo = Tapo(host, "admin", password_cloud)
  File "../pytapo_debug/pytapo/__init__.py", line 56, in __init__
    self.basicInfo = self.getBasicInfo()
  File "../pytapo_debug/pytapo/__init__.py", line 565, in getBasicInfo
    return self.executeFunction(
  File "../pytapo_debug/pytapo/__init__.py", line 152, in executeFunction
    data = self.performRequest(
  File "../pytapo_debug/pytapo/__init__.py", line 211, in performRequest
    if not self.responseIsOK(res):
  File "../pytapo_debug/pytapo/__init__.py", line 134, in responseIsOK
    raise Exception(
Exception: Error communicating with Tapo Camera. Status code: 500

```

**Comment by viprapp** [comment]
```
pyTapo - Version for debugging new firmware 3
getBasicInfo
executeFunction
True
admin
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'REDACTED', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
{"error_code": 0, "result": {"stok": "REDACTED", "user_group": "root", "start_seq": 0}}
200
{"error_code": 0, "result": {"stok": "REDACTED", "user_group": "root", "start_seq": 0}}
{"error_code":0,"seq":0,"result":{"response":"REDACTED"}}
Traceback (most recent call last):
  File "../pytapo_debug/test.py", line 8, in <module>
    tapo = Tapo(host, "admin", password_cloud)
  File "../pytapo_debug/pytapo/__init__.py", line 56, in __init__
    self.basicInfo = self.getBasicInfo()
  File "../pytapo_debug/pytapo/__init__.py", line 565, in getBasicInfo
    return self.executeFunction(
  File "../pytapo_debug/pytapo/__init__.py", line 152, in executeFunction
    data = self.performRequest(
  File "../pytapo_debug/pytapo/__init__.py", line 211, in performRequest
    if not self.responseIsOK(res):
  File "../pytapo_debug/pytapo/__init__.py", line 134, in responseIsOK
    raise Exception(
Exception: Error communicating with Tapo Camera. Status code: 500

```

**Comment by JurajNyiri** [comment]
Please try again, same script, just pull the latest changes in https://github.com/JurajNyiri/pytapo/tree/debug_new_firmware_sha256

**Comment by viprapp** [comment]
```
pyTapo - Version for debugging new firmware 4
getBasicInfo
executeFunction
True
admin
{'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}
{"error_code": 0, "result": {"stok": "REDACTED", "user_group": "root", "start_seq": 0}}
200
{"error_code": 0, "result": {"stok": "REDACTED", "user_group": "root", "start_seq": 0}}
{"error_code":0,"seq":0,"result":{"response":"REDACTED"}}
{'method': 'multipleRequest', 'params': {'requests': [{'method': 'getDeviceInfo', 'params': {'device_info': {'name': ['basic_info']}}}]}, 'seq': 1}
Traceback (most recent call last):
  File "../pytapo_debug2/test.py", line 8, in <module>
    tapo = Tapo(host, "admin", password_cloud)
  File "../pytapo_debug2/pytapo/__init__.py", line 57, in __init__
    self.basicInfo = self.getBasicInfo()
  File "../pytapo_debug2/pytapo/__init__.py", line 570, in getBasicInfo
    return self.executeFunction(
  File "../pytapo_debug2/pytapo/__init__.py", line 153, in executeFunction
    data = self.performRequest(
  File "../pytapo_debug2/pytapo/__init__.py", line 216, in performRequest
    if not self.responseIsOK(res):
  File "../pytapo_debug2/pytapo/__init__.py", line 135, in responseIsOK
    raise Exception(
Exception: Error communicating with Tapo Camera. Status code: 500
```

Additionally, the response contains a 128-character alphanumeric string with '/' and '+' characters, which could indicate base64 encoding.

**Comment by JurajNyiri** [comment]
What is inside `{"error_code":0,"seq":0,"result":{"response":"REDACTED"}}`?

**Comment by JurajNyiri** [comment]
Another update: https://github.com/JurajNyiri/pytapo/tree/debug_new_firmware_sha256 with a clearer debugging.
Please do not redact everything, only confidential information such as password, stok, mac, dev_id and oem_id. There is no reason to redact anything other than that. I do appreciate the help but you redacted important information 3 times now and it is making debugging a lot harder.

**Comment by viprapp** [comment]
> What is inside {"error_code":0,"seq":0,"result":{"response":"REDACTED"}}?

> Additionally, the response contains a 128-character alphanumeric string with '/' and '+' characters, which could indicate base64 encoding.

It is a string that looks like this (I kept the + and / dilimeters, the rest is randomized but same charset):

`{"error_code":0,"seq":0,"result":{"response":"SaR5xPV6f/sQgudugVow4NxA7VUk9Cs81CT9Wi3h5lCVcy3Yudos5a5yGskQwJ17Pckgwze0vtu824ummnFDH+ZDtxPRYbFpDtZbwX2yE+ePmhvirznkGGZ4DQzwt5GP"}}`

**Comment by JurajNyiri** [comment]
@viprapp please run again https://github.com/JurajNyiri/pytapo/tree/debug_new_firmware_sha256

**Comment by viprapp** [comment]
```
pyTapo - Version for debugging new firmware 6
{'data': '{"method": "login", "params": {"hashed": true, "password": "REDACTED", "username": "admin"}}', 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
{"error_code": 0, "result" : { "stok": "REDACTED", "user_group": "root", "start_seq": 0}}

{'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getDeviceInfo", "params": {"device_info": {"name": ["basic_info"]}}}]}, "seq": 1}', 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
{"error_code":0,"seq":0,"result":{"response":"SaR5xPV6f/sQgudugVow4NxA7VUk9Cs81CT9Wi3h5lCVcy3Yudos5a5yGskQwJ17Pckgwze0vtu824ummnFDH+ZDtxPRYbFpDtZbwX2yE+ePmhvirznkGGZ4DQzwt5GP"}}

Traceback (most recent call last):
  File "../pytapo_debug3/test.py", line 8, in <module>
    tapo = Tapo(host, "admin", password_cloud)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../pytapo_debug3/pytapo/__init__.py", line 58, in __init__
    self.basicInfo = self.getBasicInfo()
                     ^^^^^^^^^^^^^^^^^^^
  File "../pytapo_debug3/pytapo/__init__.py", line 573, in getBasicInfo
    return self.executeFunction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "../pytapo_debug3/pytapo/__init__.py", line 158, in executeFunction
    data = self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "../pytapo_debug3/pytapo/__init__.py", line 220, in performRequest
    if not self.responseIsOK(res):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "../pytapo_debug3/pytapo/__init__.py", line 141, in responseIsOK
    raise Exception(
Exception: Error communicating with Tapo Camera. Status code: 500
```

I understand the importance of these details for debugging and appreciate your patience. As for `{"response":"SaR5xPV6f/sQgudugVow4NxA7VUk9Cs81CT9Wi3h5lCVcy3Yudos5a5yGskQwJ17Pckgwze0vtu824ummnFDH+ZDtxPRYbFpDtZbwX2yE+ePmhvirznkGGZ4DQzwt5GP"}}` if you require the actual non-randomised response, I'm willing to share it privately, once I'm clear about the type of data it represents and any potential implications for my home security setup.

**Comment by timothybuchanan** [comment]
I have two cameras like this; one is still working and the other not. I deleted the non-working and reinstalled, getting the invalid cloud password error. when I changed the passwor in the Tapo app, I noticed that it now requires seven characters but my previous password used only seven. Could this have anything to do with the problem?

**Comment by kwermeister** [comment]
> I have two cameras like this; one is still working and the other not. I deleted the non-working and reinstalled, getting the invalid cloud password error. when I changed the passwor in the Tapo app, I noticed that it now requires seven characters but my previous password used only seven. Could this have anything to do with the problem?


I think this theory is unlikely. According to Tapo, there should be 8-32 characters and "At least two types of the following characters must be included: Letters, numbers and symbols."
My current one has 20 characters with letters, numbers and symbols.

**Comment by JurajNyiri** [comment]
@viprapp it should contain whatever we requested before, in this case basic info of camera. Here is mine working example for comparison:

```
{'data': '{"method": "login", "params": {"hashed": true, "password": "REDACTED", "username": "admin"}}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
{"error_code": 0, "result" : { "stok": "REDACTED", "user_group": "root"}}

{'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getDeviceInfo", "params": {"device_info": {"name": ["basic_info"]}}}]}, "seq": 1}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
{ "result": { "responses": [ { "method": "getDeviceInfo", "result": { "device_info": { "basic_info": { "device_type": "SMART.IPCAMERA", "device_model": "C200", "device_name": "C200 1.0", "device_info": "C200 1.0 IPC", "hw_version": "1.0", "sw_version": "1.1.16 Build 211209 Rel.37726n(4555)", "device_alias": "Bedroom", "features": "3", "barcode": "", "mac": "REDACTED", "dev_id": "REDACTED", "oem_id": "REDACTED", "hw_desc": "00000000000000000000000000000000" } } }, "error_code": 0 } ] }, "error_code": 0 }

{'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getPresetConfig", "params": {"preset": {"name": ["preset"]}}}]}, "seq": 2}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
{ "result": { "responses": [ { "method": "getPresetConfig", "result": { "preset": { "preset": { "id": [ "1", "2" ], "name": [ "Privacy", "Room" ], "read_only": [ "0", "0" ], "position_pan": [ "0.920372", "-0.066701" ], "position_tilt": [ "0.716080", "0.716080" ] } } }, "error_code": 0 } ] }, "error_code": 0 }

{'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getDeviceInfo", "params": {"device_info": {"name": ["basic_info"]}}}]}, "seq": 3}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
{ "result": { "responses": [ { "method": "getDeviceInfo", "result": { "device_info": { "basic_info": { "device_type": "SMART.IPCAMERA", "device_model": "C200", "device_name": "C200 1.0", "device_info": "C200 1.0 IPC", "hw_version": "1.0", "sw_version": "1.1.16 Build 211209 Rel.37726n(4555)", "device_alias": "Bedroom", "features": "3", "barcode": "", "mac": "REDACTED", "dev_id": "REDACTED", "oem_id": "REDACTED", "hw_desc": "00000000000000000000000000000000" } } }, "error_code": 0 } ] }, "error_code": 0 }

{'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA', 'device_model': 'C200', 'device_name': 'C200 1.0', 'device_info': 'C200 1.0 IPC', 'hw_version': '1.0', 'sw_version': '1.1.16 Build 211209 Rel.37726n(4555)', 'device_alias': 'Bedroom', 'features': '3', 'barcode': '', 'mac': 'REDACTED', 'dev_id': 'REDACTED', 'oem_id': 'REDACTED', 'hw_desc': '00000000000000000000000000000000'}}}
```

If it is indeed base64 encoded string, the randomisation you introduced to obfuscate it corrupted it.

**Comment by viprapp** [comment]
> @viprapp it should contain whatever we requested before, in this case basic info of camera. Here is mine working example for comparison:
> 
> ```
> {'data': '{"method": "login", "params": {"hashed": true, "password": "REDACTED", "username": "admin"}}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
> {"error_code": 0, "result" : { "stok": "REDACTED", "user_group": "root"}}
> 
> {'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getDeviceInfo", "params": {"device_info": {"name": ["basic_info"]}}}]}, "seq": 1}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
> { "result": { "responses": [ { "method": "getDeviceInfo", "result": { "device_info": { "basic_info": { "device_type": "SMART.IPCAMERA", "device_model": "C200", "device_name": "C200 1.0", "device_info": "C200 1.0 IPC", "hw_version": "1.0", "sw_version": "1.1.16 Build 211209 Rel.37726n(4555)", "device_alias": "Bedroom", "features": "3", "barcode": "", "mac": "REDACTED", "dev_id": "REDACTED", "oem_id": "REDACTED", "hw_desc": "00000000000000000000000000000000" } } }, "error_code": 0 } ] }, "error_code": 0 }
> 
> {'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getPresetConfig", "params": {"preset": {"name": ["preset"]}}}]}, "seq": 2}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
> { "result": { "responses": [ { "method": "getPresetConfig", "result": { "preset": { "preset": { "id": [ "1", "2" ], "name": [ "Privacy", "Room" ], "read_only": [ "0", "0" ], "position_pan": [ "0.920372", "-0.066701" ], "position_tilt": [ "0.716080", "0.716080" ] } } }, "error_code": 0 } ] }, "error_code": 0 }
> 
> {'data': '{"method": "multipleRequest", "params": {"requests": [{"method": "getDeviceInfo", "params": {"device_info": {"name": ["basic_info"]}}}]}, "seq": 3}', 'headers': {'Host': '192.168.100.70', 'Referer': 'https://192.168.100.70', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
> { "result": { "responses": [ { "method": "getDeviceInfo", "result": { "device_info": { "basic_info": { "device_type": "SMART.IPCAMERA", "device_model": "C200", "device_name": "C200 1.0", "device_info": "C200 1.0 IPC", "hw_version": "1.0", "sw_version": "1.1.16 Build 211209 Rel.37726n(4555)", "device_alias": "Bedroom", "features": "3", "barcode": "", "mac": "REDACTED", "dev_id": "REDACTED", "oem_id": "REDACTED", "hw_desc": "00000000000000000000000000000000" } } }, "error_code": 0 } ] }, "error_code": 0 }
> 
> {'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA', 'device_model': 'C200', 'device_name': 'C200 1.0', 'device_info': 'C200 1.0 IPC', 'hw_version': '1.0', 'sw_version': '1.1.16 Build 211209 Rel.37726n(4555)', 'device_alias': 'Bedroom', 'features': '3', 'barcode': '', 'mac': 'REDACTED', 'dev_id': 'REDACTED', 'oem_id': 'REDACTED', 'hw_desc': '00000000000000000000000000000000'}}}
> ```
> 
> If it is indeed base64 encoded string, the randomisation you introduced to obfuscate it corrupted it.

@JurajNyiri, thank you for providing your example, it clarifies what kind of output is expected. I understand now that the base64 string likely contains the basic info of the camera which is indeed sensitive. I'm hesitant to share the full string as it likely contains details like MAC, dev_id, and oem_id.

Could you guide me on how to securely share the required info without exposing these sensitive elements?

**Comment by JurajNyiri** [comment]
Is it base64? You can decode it to confirm. Or you can send the string to me juraj.nyiri@gmail.com. Realistically there is absolutely nothing anyone can do with those data though even if you shared it here.

**Comment by viprapp** [comment]
@JurajNyiri, I've sent an email with the terminal output where only the stok is redacted. I attempted to decode the base64 string, but the standard decoder wasn't successful. It seems like it might be a different encoding or a binary data format.

**Comment by JurajNyiri** [comment]
At this point we will need someone to inspect the traffic between the app and local cameras and document the requests so that we can learn from it. 
I did not receive the firmware yet.

I am going to drop this here: https://portswigger.net/burp/documentation/desktop/mobile/config-android-device (community free version works).

**Comment by GSzabados** [comment]
Or if someone could get a link to the latest firmware:

```
POST https://[IP_ADDRESS]/stok=[TOKEN]/ds

{
	"method": "get",
	"cloud_config": {
		"name": ["upgrade_info"]
	}
}
```

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/35445496/f9da78d2-f08b-4ff3-83af-3ea879ab6d76)

**Comment by JurajNyiri** [comment]
@GSzabados https://github.com/tapo-firmware/Directory
The latest is not there yet though.

**Comment by bonvga** [comment]
Hello, 

Same issue with C210 updated to 1.3.9.

@JurajNyiri, I send you by email the exchanges collected with the local proxy after a connection with app. I hope this helps ^^

**Comment by neilhawsjones** [comment]
For what it's worth, I have 2xC210.  One is firmware 1.37 and connects & works perfectly, the other is 1.3.9 and has the "cloud password error".

**Comment by JurajNyiri** [comment]
Thank you @bonvga (also thanks for providing the camera for testing!) I now have everything I need to continue research and implement new authorization method.

**Comment by JurajNyiri** [comment]
So far I was able to find out how the new authorization works and was able to successfully replicate it - https://github.com/JurajNyiri/pytapo/blob/encryption_3/pytapo/__init__.py#L173 and I am now able to get stok just like before. The issue is with the requests now, they are all encrypted and decrypted with some algorithm and I do not know how.

This one will take a while. Summonning @depau @GSzabados I need your help!

**Comment by JurajNyiri** [comment]
This was fun.

Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.0 .

**Comment by TwKenYang** [comment]
Can I still use TC70? Because it still shows that the cloud password is wrong.
I have updated to 5.4.0
![Screenshot_2023-11-05-05-54-37-381_com tplink iot](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/122585150/e62c8cc5-039c-4a5c-a8c0-e895806e1069)
![Screenshot_2023-11-05-05-54-40-237_com tplink iot](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/122585150/c88fa1a3-dcb9-4bf0-bf54-5103eb329515)
![Screenshot_2023-11-05-05-55-46-879_io homeassistant companion android](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/122585150/b42d5d8a-ecbf-456f-bdb4-6bf6ecb62997)

**Comment by JurajNyiri** [comment]
If you are still experiencing issues:

I have pushed a new code: https://github.com/JurajNyiri/pytapo/tree/debug_new_firmware

Download it manually, and next to README.md create file test.py with content:
```
from pytapo import Tapo

# Camera
user = ""  # 3rd party account name
password_cloud = ""  # cloud password
host = ""  # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, "admin", password_cloud)
request = tapo.getBasicInfo()
print(request)
```

Post the whole output of the script, it will already have everything important redacted.

**Comment by Swampen** [comment]
The new release didn't fix it for me as I still get "Invalid cloud password"  (C210 with 1.3.9 firmware).
I tried the new code from https://github.com/JurajNyiri/pytapo/tree/debug_request (you posted the earlier debug branch).

<details>
  <summary>Local account output</summary>

```
{'data': {'method': 'login', 'params': {'encrypt_type': '3', 'username': 'homeassistant-rtsp'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': -40401, 'result': {'data': {'code': -40411, 'encrypt_type': ['1', '2'], 'key': 'REDACTED', 'nonce': 'REDACTED'}}}

{'data': {'method': 'login', 'params': {'hashed': True, 'password': 'REDACTED', 'username': 'homeassistant-rtsp'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': -40401, 'result': {'data': {'code': -40411, 'encrypt_type': ['1', '2'], 'key': 'REDACTED', 'nonce': 'REDACTED'}}}
Traceback (most recent call last):
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\ape.py", line 9, in <module>
    tapo = Tapo(host, user, password)
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 68, in __init__
    self.basicInfo = self.getBasicInfo()
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 776, in getBasicInfo
    return self.executeFunction(
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 332, in executeFunction
    data = self.performRequest(
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 371, in performRequest
    self.ensureAuthenticated()
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 88, in ensureAuthenticated
    return self.refreshStok()
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 310, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```
</details>

<details>
  <summary>Cloud account output</summary>

```
{'data': {'method': 'login', 'params': {'encrypt_type': '3', 'username': 'admin'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': -40413, 'result': {'data': {'code': -40401, 'encrypt_type': ['3'], 'key': 'REDACTED', 'nonce': 'REDACTED', 'device_confirm': 'REDACTED'}}}

{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'username': 'admin'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': -40413, 'result': {'data': {'code': -40401, 'encrypt_type': ['3'], 'key': 'REDACTED', 'nonce': 'REDACTED', 'device_confirm': 'REDACTED'}}}
Traceback (most recent call last):
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\ape.py", line 12, in <module>
    tapo = Tapo(host, "admin", password_cloud)
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 68, in __init__
    self.basicInfo = self.getBasicInfo()
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 776, in getBasicInfo
    return self.executeFunction(
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 332, in executeFunction
    data = self.performRequest(
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 371, in performRequest
    self.ensureAuthenticated()
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 88, in ensureAuthenticated
    return self.refreshStok()
  File "C:\Users\ole-m\Downloads\tapo_debug\pytapo\pytapo\__init__.py", line 306, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```
</details>

**Comment by JurajNyiri** [comment]
@Swampen Nice catch. I pushed new version with more debug logs and ability to turn off redact as we might need the actual values during debugging (send it to me via email).

You can turn off redacting like this:

```
tapo = Tapo(host, "admin", password_cloud, "", "", None, False, False)
```

At this point, just run it again. If you see "Determined actual wrong cloud password!" you need to check if you are entering actual proper cloud password (and the password camera knows about) - if you changed password recently camera might not be aware of the change especially if you have it blocked in firewall. Unblock it, restart couple of times or even factory reset might be needed (past experience) to pick up the new password immediately.

**Comment by GSzabados** [comment]
@JurajNyiri, what if the `device_confirm` is empty?

**Comment by JurajNyiri** [comment]
The authentication would fail in that case. Can it be empty though? @Swampen is it empty?

**Comment by viprapp** [comment]
Well done @JurajNyiri!
I can confirm that my C210 on 1.3.9 now works as expected again.
I have to add that I removed and added the device entry.
Maybe that is a necessary step after the update to 1.3.9.

**Comment by Swampen** [comment]
@JurajNyiri A factory reset solved it. 
Removing the device and adding it again might solve it as well as @viprapp mentioned.
Nice work!

**Comment by JurajNyiri** [comment]
Follow all the steps I listed above. Factory reset, unblock in firewall and run the script as described.

**Comment by fcachado** [comment]
I reboot once more the camera and it worked, I had to reboot a total of 3 times to make it work. Thanks for your help!

**Comment by JurajNyiri** [comment]
@fcachado you probably changes the cloud password and it had to pick it up. I do not know when it decides to get new password but factory reset / readding always does it.

**Comment by mitzu2250** [comment]
Hello,

Following your reply to #436 , please note that I haven't changed my Cloud password recently.
I know for a fact that the password is right because I logged in to the app using the password.
My firewall (router ports) are not blocked, another older firmware works on the same system.

Also, I cannot reset to factory my camera because it's in a space that is not that easily accessible.
I tried rebooting it over and over again, didn't work.

I'll try to run the script later today and come back with the output.

**Comment by JurajNyiri** [comment]
Camera doesn't agree with the password you are sending it. It is 99percent camera or user issue.

One last thing we can check - run it without redact - see  https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/436#issuecomment-1793694748 and check what is inside the device_confirm field. If it is not empty it is camera/user issue and there is nothing to fix on integration.

**Comment by mitzu2250** [comment]
Ok, not sure what to do more besides resetting it factory.

For the other camera, also a C210 but on 1.3.7, same settings (different ip of course) it works.
For this one on 1.3.9 I get the error and the device_confirm is not empty.

I will keep restarting it and trying again until it will work.

**Comment by JurajNyiri** [comment]
You can also try resetting the cloud password and trying with a new one.

**Comment by mitzu2250** [comment]
> You can also try resetting the cloud password and trying with a new one.

This did not work. 1.3.7 picked up the new password right away, 1.3.9 didn't.

**Comment by JurajNyiri** [comment]
Try sending me the clear version of logs to mail juraj.nyiri@gmail.com I can take a look if values look correct. Logs contain sha256 hash of your cloud password.

**Comment by mitzu2250** [comment]
Since we agreed that is something wrong on camera side with my setup (and might be the case for others who do not read github discussions), and even if I input the correct cloud password I cannot get the camera added again, it would be nice to be able to check a box when I get the "Invalid cloud password" message while trying to add a new device, box like "I confirm that the password is correct" and if I check that and hit submit, it will skip the initial check, add the new device (which of course will fail) but at least it will automatically try the password and I don't need to repeat the workflow over and over again.

**Comment by GSzabados** [comment]
> add the new device

And how the integration would know what to add for your device?

**Comment by JurajNyiri** [comment]
That's not possible.

**Comment by mitzu2250** [comment]
Just updated my second camera which was on 1.3.7 to 1.3.9.
It started having the same password issue, ran the debug tool before and after.

So, from my point of view, something is messing up the password storage during the firmware upgrade.

**Comment by JurajNyiri** [comment]
@mitzu2250 does the factory reset / readding to tapo app help?

**Comment by mitzu2250** [comment]
Yes, this one was in an area which allowed me to reset it.
After adding it again to the app, the debug script works, I get expected output.

After restarting the Home Assistant service everything got back to normal.

So, yes, apparently a Reset would do the trick.
I'll have to do this for my other camera too...

**Comment by rark-ha** [comment]
Moving from my closed item ([https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/442](url)

I updated to 5.4.2 but now have created issues with two further cameras (so now all 4 of my 210 models).

Trying to reload the failed setup entries doesn't do anything. When my first two entities played up, they were 'failed setup' before becoming 'migration errors' after another restart.

<img width="717" alt="Screenshot 2023-11-08 at 5 39 24 am" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/62318984/416cb025-9b78-461b-938a-d74ff7008186">

<img width="565" alt="Screenshot 2023-11-08 at 5 48 24 am" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/62318984/52d1d1d3-6be8-460b-8195-7f50a57f7d35">

**Comment by JurajNyiri** [comment]
Read above and tell us what you tried so far.

**Comment by JurajNyiri** [comment]
I just discovered what was happening to most of the users here. More details soon. 
TL&DR: You can factory reset to get it work NOW or restart HA and wait for a while.

**Comment by mitzu2250** [comment]
I tried running the debug_request even after 24h and still didn't worked so I'm not convinced that waiting is a 100% working solution. Also tried adding the camera after 24h and still got the error message. 
During this time, rebooted the camera and HA multiple times.

For now, the only 100% working solution is the Factory Reset (aka Reset button).

**Comment by JurajNyiri** [comment]
@mitzu2250 Waiting AFTER removing the camera from HA and not running any scripts, important detail.

**Comment by mitzu2250** [comment]
Just tried with the camera I removed yesterday, restarted HA, waited around 65 minutes, tried to add it, didn't work.

**Comment by JurajNyiri** [comment]
@mitzu2250 There could be multiple issues, some I can fix and some I can't that are on cameras. They added temporary suspension of account on too many failed sign ins. On update to 1.3.9 if people are still using old integration it will keep retrying to sign in using the old method, resulting in refreshing temporary ban all the time. I am working on fixing that.

**Comment by JurajNyiri** [comment]
@mitzu2250 Try with https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.3 . It is possible most of users who updated firmware got into temporary ban loop (which takes 1800 seconds). This will no longer happen, instead integration will stop retrying and ask for re-authorization. This should help user experiencing the invalid authentication data error.

**Comment by mitzu2250** [comment]
Nope, doesn't work for me. 
- removed all cameras that use the integration
- restarted the cameras
- restarted the HA instance
- waited >6 hours
- tried again
- same error on both cameras

**Comment by silfax** [comment]
Ok, I know that it's marked as 'fixed', but I'm probably dumb enough and I cannot make it work. C310, 1.3.9 firmware, integration 5.4.8. I keep getting "Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1". VLC doesn't work as well, although I remember that at some point, after the issue started, it was able to show stream2 (but not stream1). Strangely, my software NVR (Luxriot) doesn't have any issues accessing both streams of the camera with the same credentials. Can anyone point me to the right steps? Is a factory reset of the camera necessary? Thanks!

**Comment by GSzabados** [comment]
> Strangely, my software NVR (Luxriot) doesn't have any issues accessing both streams of the camera with the same credentials. Can anyone point me to the right steps? Is a factory reset of the camera necessary? Thanks!

Do you have an SD card installed or Tapo Care as well?

These devices support limited amount of stream, if you use  those options and stream to another software and use the app, then you will be unable to access the streams anymore.

**Comment by JurajNyiri** [comment]
@silfax 
This issue was fixing a different bug. You are encountering a limit of streams issue.

https://www.tp-link.com/cz/support/faq/2742/

Q3: Can multiple accounts/devices view the Tapo camera at the same time?

A: Currently, each camera can be controlled or managed by only one account on the Tapo App. You can share it with 5 different accounts at most, and these two accounts can only access live view and playback features of the camera.

Each camera also supports up to 2 simultaneous video streams. You could use up to 2 devices to view the live feed of the camera simultaneously using the Tapo App or via RTSP. You may also only view the playback of a camera using one Tapo app at a time.

**Comment by silfax** [comment]
> > Strangely, my software NVR (Luxriot) doesn't have any issues accessing both streams of the camera with the same credentials. Can anyone point me to the right steps? Is a factory reset of the camera necessary? Thanks!
> 
> Do you have an SD card installed or Tapo Care as well?
> 
> These devices support limited amount of stream, if you use those options and stream to another software and use the app, then you will be unable to access the streams anymore.

SD card installed, no Tapo Care. Whatever the reason, it started after the 1.3.9 firmware upgrade. No issues before, nothing is changed. NVR used before, camera working before under HA. 3 x C200 and 1 x C500 still working.

**Comment by silfax** [comment]
> @silfax This issue was fixing a different bug. You are encountering a limit of streams issue.
> 
> https://www.tp-link.com/cz/support/faq/2742/
> 
> Q3: Can multiple accounts/devices view the Tapo camera at the same time?
> 
> A: Currently, each camera can be controlled or managed by only one account on the Tapo App. You can share it with 5 different accounts at most, and these two accounts can only access live view and playback features of the camera.
> 
> Each camera also supports up to 2 simultaneous video streams. You could use up to 2 devices to view the live feed of the camera simultaneously using the Tapo App or via RTSP. You may also only view the playback of a camera using one Tapo app at a time.
> 
> Q4: Why can’t I use Tapo Care, SD card, and NVR at the same time?
> 
> A: Due to the limited hardware performance of the camera itself, Tapo Care works best with one of the NVR or SD card recordings.
> 
> If you are using an SD card and Tapo Care at the same time, the NVR(RTSP/ONVIF) will be disabled.
> 
> To restart the recording on the NVR, please remove the SD card from the camera.
> 
> I added it to FAQ in readme as well now.

Thanks for answering. Yeah, it seems I totally misunderstood what issue was in fact fixed.

On Q3 and Q4, I'm too unexperienced to disagree, but from my own experience, the same camera used to work in the same config, simultaneously with: NVR, HA, phone/tablet app (occasionaly). No error message before the firmware upgrade. Now I can't even add it again in HA.

**Comment by JurajNyiri** [comment]
It is official TPLink documentation, if you disagree you are most probably wrong.

Nobody but you can help you solve this issue now, it is clear what is the issue, you have all the official TPLink information why it is happening, now you need to solve it, its your environment, we do not know it.

It is not an integration issue.

**Comment by HoLy1337** [comment]
I have the same problem with my C200, Hardware version 2.0 and the 1.3.9 version... frigate can connect without problems, but the tapo control can not connect...
I tried to deactivate frigate for a while and restart my complete environment multiple times, but it looks for me like the version is the problem...

if you need more informations feel free to tell me :)

**Comment by HoLy1337** [comment]
I found a solution.
for my case the problem was that the automatic update from HACS is broken. I searched for the integration and redownloaded it, after a HA restart I was getting a migration error, then i removed the konfiguration and added the camera again, now it works again...

But I have noticed that HACS now shows 2 versions of the integration:
- Tapo Controller /hacs/repository/323923603
- Tapo: Camera Control /hacs/repository/300358676

maybe this helps others too...

**Comment by GSzabados** [comment]
Tapo Controller is a different integration:

https://github.com/petretiandrea/home-assistant-tapo-p100

It is for plugs, bulbs, etc.

**Comment by nikitiuk0** [comment]
I have 1.3.11 firmware (so two versions newer than 1.3.9) and I get the same -40401 error when trying to authenticate:
```
{'error_code': -40401, 'result': {'data': {'code': -40411, 'encrypt_type': ['1', '2'], 'key': 'XXX, 'nonce': 'XXX'}}}
```

I also used HTTP toolkit to intercept traffic from the Android app in emulator but it seems like it doesn't even try to connect and auth into camera directly via local IP, but instead sends requests remotely to https://use1-app-server.iot.i.tplinknbu.com/ 
<img width="644" alt="image" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/2797614/0cb72927-8e89-461a-9b6e-2a10fbe71624">


Was that how you folks intercepted this traffic previously? Or am I doing something differently?

**Comment by shurakr** [comment]
Everything worked stably until today.
Today HA asks to reconfigure the cameras and ends up with Invalid cloud password

**Comment by mgmorpheus77** [comment]
Hi
Does anyone of you have old firmware for the TPLink C220 camera?

**Comment by jeffreydahan** [comment]
Hi there, I just purchased a Model C320WS, hardware version 2.0, firmware 1.3.5 (latest).  I am using the latest pytapo.  I went through all of the above steps, but consistently get the Exception:  Invalid authentication data (I have tried "admin" and my 3rd party tapo user/password).  Does anyone have this working?  I am trying to simply connect with python.  Thanks!
