### ISSUE TITLE
Warning: Detected blocking call to open inside the event loop by custom integration 'tapo_control'

### ISSUE THREAD

**Issue by catalinbordan** [JurajNyiri/HomeAssistant-Tapo-Control#612]
### Description

I think it is coming from new version of Home Assistant 2024.6.3
Almost 19k hits from the last 12h.
I also have this warning: Recording is currently in progress.
I did not see any issues in regarding the use of integration.

### Reproduction Steps

I had activated media sync for all my 3 cameras in /media/tapo

### Expected behavior

no warning about

### If applicable, add error logs.

Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 17 June 2024 at 19:35:02 (18096 occurrences)
Last logged: 10:40:11

Detected blocking call to open inside the event loop by custom integration 'tapo_control' at custom_components/tapo_control/utils.py, line 513: downloadedFile = await downloader.downloadFile( (offender: /usr/local/lib/python3.12/site-packages/pytapo/media_stream/convert.py, line 25: file = open(tempVideoFileLocation, "wb")), please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/tapo_control/__init__.py", line 752, in mediaSync await getRecording( File "/config/custom_components/tapo_control/utils.py", line 513, in getRecording downloadedFile = await downloader.downloadFile(
Detected blocking call to open inside the event loop by custom integration 'tapo_control' at custom_components/tapo_control/utils.py, line 513: downloadedFile = await downloader.downloadFile( (offender: /usr/local/lib/python3.12/site-packages/pytapo/media_stream/convert.py, line 29: file = open(tempAudioFileLocation, "wb")), please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/tapo_control/__init__.py", line 752, in mediaSync await getRecording( File "/config/custom_components/tapo_control/utils.py", line 513, in getRecording downloadedFile = await downloader.downloadFile(
Detected blocking call to open inside the event loop by custom integration 'tapo_control' at custom_components/tapo_control/utils.py, line 513: downloadedFile = await downloader.downloadFile( (offender: /usr/local/lib/python3.12/site-packages/pytapo/media_stream/downloader.py, line 45: with open(fileName, "rb") as f:), please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/tapo_control/__init__.py", line 752, in mediaSync await getRecording( File "/config/custom_components/tapo_control/utils.py", line 513, in getRecording downloadedFile = await downloader.downloadFile(
Detected blocking call to open inside the event loop by custom integration 'tapo_control' at custom_components/tapo_control/utils.py, line 265: with open(filePathThumb, "wb") as binary_file: (offender: /config/custom_components/tapo_control/utils.py, line 265: with open(filePathThumb, "wb") as binary_file:), please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/tapo_control/__init__.py", line 752, in mediaSync await getRecording( File "/config/custom_components/tapo_control/utils.py", line 540, in getRecording await processDownload( File "/config/custom_components/tapo_control/utils.py", line 233, in processDownload await generateThumb( File "/config/custom_components/tapo_control/utils.py", line 265, in generateThumb with open(filePathThumb, "wb") as binary_file:

### Device Firmware

last fw without issues related to cloud pswd

### Integration Version

5.4.18

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home assistant on VM

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.19.

**Comment by catalinbordan** [comment]
thank you very much!
I installed right now and I still have some issues.
please see bellow:


```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 16:32:16 (2 occurrences)
Last logged: 16:32:16

Detected blocking call to open with args ('/media/tapo/door/thumbs/1720087612-1720087690.jpg', 'rb') inside the event loop by custom integration 'tapo_control' at custom_components/tapo_control/utils.py, line 480: shutil.copyfile(coldFilePath, hotFilePath) (offender: /usr/local/lib/python3.12/shutil.py, line 260: with open(src, 'rb') as fsrc:), please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response await func(hass, connection, msg) File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 187, in websocket_browse_media media = await async_browse_media(hass, msg.get("media_content_id", "")) File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 135, in async_browse_media item = await _get_media_item(hass, media_content_id, None).async_browse() File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 80, in async_browse return await self.async_media_source().async_browse_media(self) File "/config/custom_components/tapo_control/media_source.py", line 214, in async_browse_media thumbLink = getWebFile( File "/config/custom_components/tapo_control/utils.py", line 487, in getWebFile hotFilePath = getHotFile(hass, entry_id, startDate, endDate, folder) File "/config/custom_components/tapo_control/utils.py", line 480, in getHotFile shutil.copyfile(coldFilePath, hotFilePath)
Detected blocking call to open with args ('/config/www/tapo_control/523721c162e428d5ccfbfb8d32989b3b/thumbs/cdc256ee01e6377337adcf53fd129fc422f00b17ccac45a990a9c322bfbe6414.jpg', 'wb') inside the event loop by custom integration 'tapo_control' at custom_components/tapo_control/utils.py, line 480: shutil.copyfile(coldFilePath, hotFilePath) (offender: /usr/local/lib/python3.12/shutil.py, line 262: with open(dst, 'wb') as fdst:), please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response await func(hass, connection, msg) File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 187, in websocket_browse_media media = await async_browse_media(hass, msg.get("media_content_id", "")) File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 135, in async_browse_media item = await _get_media_item(hass, media_content_id, None).async_browse() File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 80, in async_browse return await self.async_media_source().async_browse_media(self) File "/config/custom_components/tapo_control/media_source.py", line 214, in async_browse_media thumbLink = getWebFile( File "/config/custom_components/tapo_control/utils.py", line 487, in getWebFile hotFilePath = getHotFile(hass, entry_id, startDate, endDate, folder) File "/config/custom_components/tapo_control/utils.py", line 480, in getHotFile shutil.copyfile(coldFilePath, hotFilePath)

```

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.20 .

**Comment by JurajNyiri** [comment]
@catalinbordan when you try to play a recording via HA, it needs to copy it into the HA www folder temporarily.

**Comment by catalinbordan** [comment]
thanks for explanations and for the updated code. I have installed, restarted and again watched some videos. seems ok, no errors.
I will check later if I will find some files lost/not deleted.
You are the best :)
