### ISSUE TITLE
Tapo C210 : ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.xxx.xxx

### ISSUE THREAD

**Issue by jymorel** [JurajNyiri/HomeAssistant-Tapo-Control#972]
### Description

Hi,
I have 4 TP-LINK Tapo cameras. 2 C310 and 2 C210, which are up to date with the latest firmware versions.
For the past few days/weeks, one of the 2 C210 has been systematically generating errors every 10 minutes in the logs. The others C210 and  C310 work perfectly without any errors. 
I've removed and added the camera integration several times, but still the issue.
I noticed that the "time synchronization" option is not available for this camera. The "button.camera_salon_tapo_c210_sync_time" entity has a status of "unknown" (error "Failed to execute action button/press. int() argument must be a string, a bytes-like object, or a real number, not 'NoneType'" when I click on it). Unable to check the option in the integration configuration.
Any idea?
Thank you

![Image](https://github.com/user-attachments/assets/88558157-45e7-4402-a261-cf3caf5bb5e8)

### Reproduction Steps

.

### Expected behavior

.

### If applicable, add error logs.

2025-06-07 00:50:57.760 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547037662400] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 250, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tapo_control/button.py", line 141, in async_press
    await syncTime(self._hass, self._entry_id)
  File "/config/custom_components/tapo_control/utils.py", line 1626, in syncTime
    timeSyncDST = int(hass.data[DOMAIN][entry_id][TIME_SYNC_DST])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**EVERY 10 minutes:**
2025-06-07 00:53:13.628 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.51
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^

### Device Firmware

1.4.6 Build 250415 Rel.53604n

### Integration Version

6.1.7

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS 2025.5.3

### Search for similar issues

Yes

### Additional information

_No response_

**Comment by JurajNyiri** [comment]
Have you added this camera recently as a new device?

**Comment by JurajNyiri** [comment]
Should be fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/6.1.8. You will need to remove the camera and add it again, **or** modify the entry under `.storage/core.config_entries` by adding:

```
"time_sync_dst": 1,
"time_sync_ndst": 0,
```

under the entry for the specific camera that is missing it.

**Comment by jymorel** [comment]
ok, waiting for the new release. Thank you for the quick answer

**Comment by jymorel** [comment]
6.1.8 installed. I removed the camera and added it again. Sync time button is ok now (state "unknown"... ?).
But i still get errors every 10 minutes : 

2025-06-07 12:49:55.729 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.51
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-07 12:49:57.032 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.51
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-07 12:49:58.337 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.51
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00\x8c4\xe0\xb6\x19\xbb\xec\xb6'
          ^
2025-06-07 12:49:59.639 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.51
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x003'
          ^
2025-06-07 12:50:00.942 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.51
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00\x8c4\xe0\xb6\x19\xbb\xec\xb6'
          ^

**Comment by JurajNyiri** [comment]
Does the error stop if camera is disabled in this integration? To verify it is coming from this integration as logs do not specify it.

If yes, 

1. Enable debug logs and post here
2. most likely this specific camera does not support onvif standard properly (and therefore time sync). Simply disable the automatic time sync and see if the error stops.

**Comment by jymorel** [comment]
The integration has nothing to do with this problem.
I get the same error when it's disabled or when I remove the camera from the integration.
I disabled Time Sync, same error.
I also tried disabling the Frigate integration (I have Frigate installed on another Raspberry Pi running OpenMediaVault), same error.
I also uninstalled Go2RTC and WebRTC Camera, same error. And now, since yesterday, the second C210 is producing the same errors every 10 minutes...
I also have messages in the go2rtc logs like:
"undefined error=EOF url=rtsp://user:password@192.168.1.100:554/stream1 caller=github.com/AlexxIT/go2rtc/internal/streams/prod
undefined error=EOF url=rtsp://user:password@192.168.1.51:554/stream1 caller=github.com/AlexxIT/go2rtc/internal/streams/prod"
The two C210 IPs.
Completely lost...

**Comment by jymorel** [comment]
Sorry for asking you for nothing...
My memory is unreliable. I had the same problem in the past with my two C310s and I already had ignored these messages in logger for those cameras. I'll do the same for my two C210s. 
I just found the post that mentions these unimportant messages...
[(https://github.com/aio-libs/aiohttp/issues/10331#issuecomment-2645589854)]
Thank you

**Comment by Matze89x** [comment]
Hello to you, I have been experiencing the same errors for months now and can't seem to ... firmware update back to 1.4.1... The problem is still there today with the latest 1.4.3.

The only workaround I could come up with temporarily was to create a firewall in Proxmox on the Home Assistant virtual machine.
```
2025-06-26 22:41:33.585 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.52
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:34.941 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.52
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:36.252 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.52
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:37.556 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.52
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:44.361 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.53
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00\xff'
          ^
2025-06-26 22:41:45.664 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.53
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:46.966 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.53
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:48.269 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.53
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
2025-06-26 22:41:49.577 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.53
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 408, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Data after `Connection: close`:
    b'\x00'
          ^
```


<img width="984" alt="Image" src="https://github.com/user-attachments/assets/baa08536-2129-4d36-b622-0c43ec3cc385" />

Now it's quiet for the time being...

**Comment by nanomonster** [comment]
`Should be fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/6.1.8. You will need to remove the camera and add it again, or modify the entry under .storage/core.config_entries`

Hi, I wanted to update to 6.1.8.  I tried disabling the cameras but then the integration disappeared from the available services! (not what I expected).  I'm trying to add it again but I get an error saying the IPs of the cameras I am using are already configured... and  I can't go any further. help!

**Comment by nanomonster** [comment]
@JurajNyiri  Can I at least get an acknowledgement of my query please?
